import React from 'react'
import type { Metadata } from 'next'
import { apiPlugin, storyblokInit } from '@storyblok/react/rsc'

export const metadata: Metadata = {
	title: 'Web Documentation',
	description: 'Generated by Next.js',
}

storyblokInit({
	accessToken: process.env.STORYBLOK_TOKEN,
	use: [apiPlugin],
	apiOptions: {
		region: 'us',
	},
})

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return <StoryblokProvider>{children}</StoryblokProvider>
}
